// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtucpyppsjeswzzfqvsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0dWNweXBwc2plc3d6emZxdnNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NTMyMTUsImV4cCI6MjA3NjAyOTIxNX0.j__DBo3LZyyb7bAzI7W_GutAPMgLLBxzixfxFQO_nco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});